import Elemento3 from "../../../assets/images/elements/elemento3.jpg";

let footer = `

  <div> 
    <p>
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
      Texto do site....Texto do site....Texto do site....Texto do site....
    </p>

    <img src="${Elemento3}" alt="elemento3" heigth="180px" width="auto"
    >

  </div>

`;

export default footer;
